server:
  port: 1006
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: user-service
    api-b:
      path: /api-b/**
      serviceId: user-fegin-consumer

management:
  security:
    enabled: false