server:
  port: 1000
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-enreka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
#management:
#  security:
#    enabled: false